apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 2
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: webapp-angular:1.0
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production-microservice

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
spec:
  selector:
    matchLabels:
      app: queue
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: queue
    spec:
      containers:
        - name: queue
          image: queue:1.0

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: forklift-mock-simulator
spec:
  selector:
    matchLabels:
      app: forklift-mock-simulator
  replicas: 1
  template:
    metadata:
      labels:
        app: forklift-mock-simulator
    spec:
      containers:
        - name: position-simulator
          image: forklift-mock-simulator:1.0
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production-microservice

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-tracker
spec:
  selector:
    matchLabels:
      app: position-tracker
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: position-tracker
    spec:
      containers:
        - name: position-tracker
          image: forklift-position-tracker:1.0
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production-microservice

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: api-gateway:1.0
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production-microservice
